docker/web/base/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',IndexView.as_view(),name='index'),
    path('dataset/',DatasetListView.as_view(),name='dataset_list',),
    path('dataset/create',DatasetCreateView.as_view(),name='dataset_create'),
    path('dataset/delete/<int:pk>', DatasetDeleteView.as_view(), name='dataset_delete'),
    path('dataset/view/<int:pk>', DatasetViewView.as_view(), name='dataset_view'),

    path('ajax/get_dataset_columns', ajax_get_dataset_columns, name='ajax_get_dataset_columns'),
]
urlpatterns += [
    path(r'regression/', include('regression.urls', namespace='regression')),
]

docker/web/regression/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'Regression'

urlpatterns = [
    path('', RegressionListView.as_view(), name='regression_list',),
    path('create', RegressionCreateView.as_view(), name='regression_create'),
    path('delete/<int:pk>', RegressionDeleteView.as_view(), name='regression_delete'),
    path('view/<int:pk>', RegressionViewView.as_view(), name='regression_view'),
]

docker/web/regression/models/regression.py
from django.db import models
from base.models.analysis import Analysis
from base.models.dataset import Dataset


class Regression(Analysis):
    blah = 5

docker/web/regression/views/regression.py
from datetime import datetime
from django import forms
from django.contrib import messages
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import View
from regression.models import Regression
from regression.models import Regression
from base.models.dataset import Dataset
from sklearn.linear_model import LinearRegression
from base.redis_db import RedisDB


class RegressionCreateForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    dataset = forms.ModelChoiceField(queryset=Dataset.objects.all())
    dependent_column = forms.ChoiceField()
    independent_columns = forms.MultipleChoiceField()

    def clean(self):
        super(RegressionCreateForm, self).clean()
        del self.errors["independent_columns"]
        del self.errors["dependent_column"]


class RegressionListView(View):
    def get(self, request, *args, **kwargs):
        model = Regression.objects.all().order_by("id").reverse()
        return render(
            request, "regression/regression_list.html", {"regression_list": model}
        )


class RegressionCreateView(View):
    form_class = RegressionCreateForm
    template_name = "regression/regression_create.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            a_regression = Regression(
                name=form.cleaned_data["name"],
                created=datetime.now(),
                dataset=form.cleaned_data["dataset"],
                independent_columns=request.POST.getlist("independent_columns"),
                dependent_column=form.data["dependent_column"],
            )
            # do regression
            my_redis = RedisDB(a_regression.dataset.id)
            df = my_redis.get_df('dataframe')
            lr = LinearRegression()
            lr.fit(df[a_regression.independent_columns], df[a_regression.dependent_column])
            a_regression.set_results(lr)
            a_regression.save()
            messages.success(request, "Regression added.")
            return redirect("/regression")
        else:
            return render(request, self.template_name, {"form": form})


class RegressionDeleteView(View):
    def get(self, request, *args, **kwargs):
        regression_id = kwargs["pk"]
        Regression.objects.filter(id=regression_id).delete()
        messages.success(request, "Regression deleted.")
        return redirect("/regression")


class RegressionViewView(View):
    def get(self, request, *args, **kwargs):
        regression_id = kwargs["pk"]
        html = f"regression_id: {regression_id}<br/>"
        return render(request, "regression/regression_view.html", {"html": html})

docker/web/regression/templates/regression/regression_create.html
{% extends 'regression/regression_list.html' %}
{% load django_bootstrap_breadcrumbs %}
{% block title %}Create Dataset{% endblock title %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Create Regression' '/regression/create' %}
{% endblock %}
{% block javascript_page %}
    <script type="text/javascript">
        function pagejq() {
            // set members when field changes
            $("#id_dataset").change(function () {
                $.ajax({
                    url: '/ajax/get_dataset_columns',
                    data: {
                        //'field': this.value,
                        'dataset_id': $('#id_dataset').val()
                    },
                    dataType: 'json',
                    success: function (data) {
                        $('#id_independent_columns').empty();
                        $.each(data, function (i,item) {
                            $('#id_independent_columns').append($('<option>').text(item).attr('value', item));
                        });
                        $('#id_dependent_column').empty();
                        $.each(data, function (i,item) {
                            $('#id_dependent_column').append($('<option>').text(item).attr('value', item));
                        });
                    }
                });
            });
        }
    </script>
{% endblock javascript_page %}
{% block content %}
{% include "base/model_add.html" %}
{% endblock %}

docker/web/regression/templates/regression/regression_list.html
{% extends 'base/index.html' %}
{% load base_tags  %}
{% load django_bootstrap_breadcrumbs %}
{% block title %}Regression List{% endblock title %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Regression List' '/regression' %}
{% endblock %}

{% block content %}
    <div align="center" class="formBorder">
        <a href="/regression/create">Create Regression</a>
        {% if regression_list %}
            <table class="table table-striped table-light table-bordered table-sm m-0">
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>created</th>
                    <th>dataset</th>
                    <th>dependent column</th>
                    <th>independent columns</th>
                    <th>view</th>
                    <th>delete</th>
                    <th>Jupyterlab</th>
                </tr>
                {% for regression in regression_list %}
                <tr>
                    <td>{{ regression.id }}</td>
                    <td>{{ regression.name }}</td>
                    <td>{{ regression.created }}</td>
                    <td>{{regression.dataset}}</td>
                    <td>{{regression.dependent_column}}</td>
                    <td>{{regression.independent_columns}}</td>
                    <td><a href="view/{{ regression.id }}">view</a></td>
                    <td><a href="delete/{{ regression.id }}">delete</a></td>
                    <th>Jupyterlab</th>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <p>There are no regressions.</p>
            {% endif %}
    </div>
{% endblock %}

docker/web/regression/templates/regression/regression_view.html
{% extends 'regression/regression_list.html' %}
{% load django_bootstrap_breadcrumbs %}
{% block title %}View Regression{% endblock title %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'View Regression' '/regression/view' %}
{% endblock %}

{% block content %}
{{ html|safe}}
{% endblock %}